**Pandas Cleaning**

Refers to fixing bad data in your data set.

*Bad Data Could be:*
1. Empty cells
2. Data in wrong format
3. Wrong data
4. Duplicates

In [2]:
import pandas as pd

In [4]:
#lets load our csv
df_data=pd.read_csv('sample_data/data.csv')

#display
df_data.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [30]:
df_data.shape[0]

169

In [5]:
#lets add a messy date column to the dataframe=---This will be perfect for cleaning
import numpy as np
import random


# assume your DataFrame is called df with 169 rows
n = len(df_data)   # should be 169

# generate messy dates
bad_dates = []
for i in range(n):
    choice = random.choice([1, 2, 3, 4, 5])
    if choice == 1:
        bad_dates.append("2023-01-{:02d}".format((i % 28) + 1))  # YYYY-MM-DD
    elif choice == 2:
        bad_dates.append("01/{:02d}/2023".format((i % 28) + 1))  # MM/DD/YYYY
    elif choice == 3:
        bad_dates.append("202301{:02d}".format((i % 28) + 1))    # YYYYMMDD
    elif choice == 4:
        bad_dates.append("Jan {:02d}, 2023".format((i % 28) + 1)) # text format
    else:
        bad_dates.append(np.nan)  # missing value

# add as new column
df_data["Date"] = bad_dates

# preview
print(df_data.head(10))

   Duration  Pulse  Maxpulse  Calories          Date
0        60    110       130     409.1    01/01/2023
1        60    117       145     479.0    2023-01-02
2        60    103       135     340.0           NaN
3        45    109       175     282.4  Jan 04, 2023
4        45    117       148     406.0    01/05/2023
5        60    102       127     300.0    2023-01-06
6        60    110       136     374.0           NaN
7        45    104       134     253.3           NaN
8        30    109       133     195.1      20230109
9        60     98       124     269.0           NaN

In [32]:
#display the dataframe
df_data

     Duration  Pulse  Maxpulse  Calories          Date
0          60    110       130     409.1      20230101
1          60    117       145     479.0      20230102
2          60    103       135     340.0    2023-01-03
3          45    109       175     282.4    2023-01-04
4          45    117       148     406.0    01/05/2023
..        ...    ...       ...       ...           ...
164        60    105       140     290.8    2023-01-25
165        60    110       145     300.0  Jan 26, 2023
166        60    115       145     310.2    2023-01-27
167        75    120       150     320.4           NaN
168        75    125       150     330.4    01/01/2023

[169 rows x 5 columns]

In [33]:
#lets see how many null values are in each column. Use the isnull() method to identify null values
df_data.isnull().sum()   #we know the date column has plenty of null values

Duration     0
Pulse        0
Maxpulse     0
Calories     5
Date        31
dtype: int64

**Empty Cells**

Empty cells can potentially give you wrong result when you analyze data


**Remove Rows**

One way to deal with empty cells is to remove rows that contain empty cells

*NOTE*: This is ok because data sets can be very big, and removing a few rows will not have a big impact on the result.

**dropna()** method can perform this on our dataframe


N/B: dropna() method returns a new DataFrame and will not change the original. If we want to change the original dataframe add the **inplace=True** argument.

In [6]:
#lets drop all null values in our loaded data frame
new_df=df_data.dropna()

#display
new_df

     Duration  Pulse  Maxpulse  Calories        Date
1          60    117       145     479.0  01/02/2023
2          60    103       135     340.0  2023-01-03
3          45    109       175     282.4  01/04/2023
4          45    117       148     406.0    20230105
5          60    102       127     300.0  2023-01-06
..        ...    ...       ...       ...         ...
162        45     95       130     270.0  2023-01-23
163        45    100       140     280.9  01/24/2023
165        60    110       145     300.0    20230126
166        60    115       145     310.2    20230127
168        75    125       150     330.4  01/01/2023

[131 rows x 5 columns]

In [9]:
#check if there are any null values in any column
new_df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
Date        0
dtype: int64

**Replace Empty Values**

Another way of dealing with empty cells is to insert a new value instead.

This prevents deleting entire rows just because of some empty cells

**fillna()** method allows us to replace empty cells with a value we choose.

In [11]:
df_replace=df_data   #make a copy of our dataframe

df_replace.head(4)

   Duration  Pulse  Maxpulse  Calories        Date
0        60    110       130     409.1         NaN
1        60    117       145     479.0  01/02/2023
2        60    103       135     340.0  2023-01-03
3        45    109       175     282.4  01/04/2023

In [19]:
#check the null values inthe Calories column
df_replace['Calories'].isnull().sum()

np.int64(5)

In [20]:
#lets replace the Calories column Null values with the number 130

df_replace.fillna({"Calories":130}, inplace=True)

In [21]:
#lets check the five null rows have the value 130
df_replace[df_replace["Calories"]==130]   #they should be five

     Duration  Pulse  Maxpulse  Calories          Date
17         45     90       112     130.0           NaN
27         60    103       132     130.0  Jan 28, 2023
91         45    107       137     130.0  Jan 08, 2023
118        60    105       125     130.0      20230107
141        60     97       127     130.0    2023-01-02

**Replace Using Mean, Median, or Mode**

A common way to replace empty cells is to calculate the mean, median or mode value of the column.

Pandas uses the **Mean()**, **Median()**, **Mode()** methods to calculate the respoective values for a specified column

**a)Mean()**

 the arithmetic average of a group of numbers, calculated by summing all values and dividing by the total number of values

 We use the .mean() method in pandas

In [34]:
#make a copy of the data frame
df_mean_replace=df_data

In [35]:
#Calculate the MEAN() of the column with null values
x=df_mean_replace['Calories'].mean().round(2)

#display the mean
print(x)

375.79

In [36]:
#now use the calculated mean above stored in 'x' to replace the null values
df_mean_replace.fillna({'Calories':x}, inplace=True)

In [37]:
#now lets check the 5 empty rows inthe Calories column if filled by the mean
df_mean_replace[df_mean_replace['Calories']==375.79]

     Duration  Pulse  Maxpulse  Calories          Date
17         45     90       112    375.79    2023-01-18
27         60    103       132    375.79  Jan 28, 2023
91         45    107       137    375.79    2023-01-08
118        60    105       125    375.79    2023-01-07
141        60     97       127    375.79      20230102

**b)MEDIAN()**

Refers to the middle value in a data set that has been ordered from the least to greatest.  Represents the 50th percentile meaning that half the data points are below it and half are above it.

In [40]:
#load the dataset
df_median_replace=pd.read_csv('sample_data/data.csv')

In [41]:
#check null values in calories
df_median_replace.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [42]:
#get the median
x=df_median_replace['Calories'].median()

#display
print(x)

318.6

In [43]:
#Now add the calculated median to all the values
df_median_replace.fillna({'Calories':x},inplace=True)

In [44]:
#check if the 5 rows have the median value inthe calories column
df_median_replace[df_median_replace['Calories']==318.6]

     Duration  Pulse  Maxpulse  Calories
17         45     90       112     318.6
27         60    103       132     318.6
91         45    107       137     318.6
118        60    105       125     318.6
141        60     97       127     318.6

**c)MODE()**

Refers to the value that appears most frequently in a data set.

In [45]:
#load the dataset
df_mode_replace=pd.read_csv('sample_data/data.csv')

In [47]:
#we know the calories column has the null 5 null values
#Lets calculate the mode and get the first element of te result
x=df_mode_replace['Calories'].mode()[0]

#display
print(x)

300.0

In [48]:
#use the mode we got to replace the value
df_mode_replace.fillna({'Calories':x}, inplace=True)

In [49]:
#check the 5 rows, Remember Mode is the value that reappears so the answer will be more than 5 rows
df_mode_replace[df_mode_replace['Calories']==300.0]

     Duration  Pulse  Maxpulse  Calories
5          60    102       127     300.0
16         60    100       120     300.0
17         45     90       112     300.0
22         60    130       101     300.0
27         60    103       132     300.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
47         45    111       136     300.0
77         45    110       141     300.0
85         30    151       170     300.0
91         45    107       137     300.0
118        60    105       125     300.0
141        60     97       127     300.0
165        60    110       145     300.0

# **Cleaning Data of Wrong Format**

Cells with wrong data format make it difficult to analyze data.

To fix it you have two options:
1. Remove the rows
2. Convert the cells inthe column into the same format

**Convert Into a Correct Format**

In our data frame the date column has date formats not of the correct format and contains null values

**to_datetime()** method can convert the column values into dates

In [6]:
df_data.head() #display the dataframe

   Duration  Pulse  Maxpulse  Calories          Date
0        60    110       130     409.1    01/01/2023
1        60    117       145     479.0    2023-01-02
2        60    103       135     340.0           NaN
3        45    109       175     282.4  Jan 04, 2023
4        45    117       148     406.0    01/05/2023

In [7]:
#lets convert all cells inthe "Date Column into dates" format='mixed' tells pandas to not assume and get all formats from the column
df_data['Date']=pd.to_datetime(df_data['Date'], format='mixed')

In [10]:
#Check the datframe now
df_data

     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2023-01-01
1          60    117       145     479.0 2023-01-02
2          60    103       135     340.0        NaT
3          45    109       175     282.4 2023-01-04
4          45    117       148     406.0 2023-01-05
..        ...    ...       ...       ...        ...
164        60    105       140     290.8 2023-01-25
165        60    110       145     300.0 2023-01-26
166        60    115       145     310.2 2023-01-27
167        75    120       150     320.4 2023-01-28
168        75    125       150     330.4        NaT

[169 rows x 5 columns]

In [11]:
#check the null values inthe columns
df_data.isnull().sum()

Duration     0
Pulse        0
Maxpulse     0
Calories     5
Date        37
dtype: int64

In [14]:
#lets clean now the column by droping rows with null values from our dataframe
df_data.dropna(inplace=True)

In [16]:
df_data.isnull().sum() #check if there are any null values

Duration    0
Pulse       0
Maxpulse    0
Calories    0
Date        0
dtype: int64

**Example: to_datetime() Method**

In [20]:
#lets create our dataframe object(contains two series)
activity={
    "Date":["2023-01-01", "01/02/2023", "20230103", "Jan 04, 2023", None],
    "Activities":['Running','Skating','Gym Work', 'Football','Coding']
}

df_activities=pd.DataFrame(activity)

In [18]:
#display our dataframe
df_activities

           Date Activities
0    2023-01-01    Running
1    01/02/2023    Skating
2      20230103   Gym Work
3  Jan 04, 2023   Football
4          None     Coding

In [23]:
#lets clean the messy date column in one go
df_activities['Date']=pd.to_datetime(df_activities['Date'], format='mixed')

#display the cleaned dataframe
df_activities

        Date Activities
0 2023-01-01    Running
1 2023-01-02    Skating
2 2023-01-03   Gym Work
3 2023-01-04   Football
4        NaT     Coding

**NOTE**:
1. All formats inthe dataframe are unified to YYYY-MM-DD
2. The missing value becomes NaT(Not a Time) which is the datetime's version of NaN

# **Fixing Wrong Data**

**Wrong Data**

Does not have to be empty cells or wrong formats but it can just be wrong e.g someone registering "199" instead of "1.99"


In our dataframe we can say that a person working out more than 120 minutes isnt mostly realistic as majority of the data lies between 60 minutes to 100 minutes. They may have made an error.

In [25]:
#Identify the different values inthe column and how many they are
df_data['Duration'].value_counts()

Duration
60     58
45     28
30     11
20      8
90      7
180     3
160     2
15      2
150     2
80      1
270     1
120     1
25      1
210     1
75      1
Name: count, dtype: int64

In [28]:
#lets display all rows that are above 120 minutes
df_data[df_data['Duration']>120]

     Duration  Pulse  Maxpulse  Calories       Date
61        160    110       137    1034.4 2023-01-06
62        160    109       135     853.0 2023-01-07
65        180     90       130     800.4 2023-01-10
66        150    105       135     873.4 2023-01-11
73        150     97       127     953.2 2023-01-18
79        270    100       131    1729.0 2023-01-24
90        180    101       127     600.1 2023-01-07
106       180     90       120     800.3 2023-01-23
109       210    137       184    1860.4 2023-01-26

In [29]:
#Lets get the median and set on these rows
y=df_data['Duration'].median()

#display
print(y)

60.0

In [30]:
#now lets loop through all the values inthe duration column and set anything higher than 120 to the median value
for x in df_data.index:
  #we access the exact row using its index and the second argument is the column name
  if df_data.loc[x, "Duration"]>120:
    #lets set the value to 60 which is our calculated median
    df_data.loc[x, "Duration"]=y

In [31]:
#check it now
df_data['Duration'].value_counts()

Duration
60     67
45     28
30     11
20      8
90      7
15      2
80      1
120     1
25      1
75      1
Name: count, dtype: int64

# **Removing Duplicates**

Duplicates are rows that have been registered more than one time.

To discover about duplicates we use the **duplicated()** method- returns Bools of each row.

In [33]:
#lets look if our dataframe has duplicates
df_data.duplicated().sum()   #our dataframe has no duplicates

np.int64(0)

**Removing Duplicates**

To remove duplicates, use the drop_duplicates() method

In [34]:
#create object
company={
    "Name":['Allan','Jaba','Rembo','Mark','Allan','Alvin'],
    'Languages':['Python','JS','SQL','Bash','Python','C/C++'],
    'Salary':[40000, 86999,30000,150000,40000,100000]
}

#load dataframe
df_company=pd.DataFrame(company)

#display
df_company

    Name Languages  Salary
0  Allan    Python   40000
1   Jaba        JS   86999
2  Rembo       SQL   30000
3   Mark      Bash  150000
4  Allan    Python   40000
5  Alvin     C/C++  100000

In [36]:
#lets identify duplicates
df_company.duplicated().value_counts()

False    5
True     1
Name: count, dtype: int64

In [39]:
#we got one duplicated row, drop it. Add inplace=True
df_company.drop_duplicates(inplace=True)

In [40]:
#display new df
df_company

    Name Languages  Salary
0  Allan    Python   40000
1   Jaba        JS   86999
2  Rembo       SQL   30000
3   Mark      Bash  150000
5  Alvin     C/C++  100000