In [1]:
import pandas as pd

In [15]:
nfl_data=pd.read_csv('sample_data/nfl_data.csv')

nfl_data

/tmp/ipython-input-301766132.py:1: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  nfl_data=pd.read_csv('sample_data/nfl_data.csv')

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009.0
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009.0
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009.0
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009.0
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150883,2012-10-21,2012102101,4,1,1.0,01:19,2,2779.0,38.0,MIN,...,NaN,0.611922,0.388078,0.628062,0.371938,0.388078,-0.016140,NaN,NaN,2012.0
150884,2012-10-21,2012102101,4,1,2.0,00:31,1,2731.0,48.0,MIN,...,NaN,0.628062,0.371938,0.724615,0.275385,0.371938,-0.096553,NaN,NaN,2012.0
150885,2012-10-21,2012102101,5,1,1.0,00:20,1,2720.0,11.0,MIN,...,NaN,0.724615,0.275385,0.685293,0.314707,0.724615,-0.039322,NaN,NaN,2012.0
150886,2012-10-21,2012102101,5,1,NaN,00:00,0,2700.0,20.0,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2012.0
150887,2012-10-21,2012102101,5,2,2.0,15:00,15,2700.0,0.0,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Handling Missing Values**

Data Cleaning involves handling missing values, incorrect column formats and inconsistent data entry.

**1. Take a first look at the data**

This gives us an idead of whats going on with the data.

In [4]:
#get the first 5 rows
nfl_data.head()  #we see missing values already

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009.0
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009.0
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009.0
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009.0
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009.0

In [5]:
col_list=list(nfl_data.columns)

for i in col_list:
  print(i)

Date
GameID
Drive
qtr
down
time
TimeUnder
TimeSecs
PlayTimeDiff
SideofField
yrdln
yrdline100
ydstogo
ydsnet
GoalToGo
FirstDown
posteam
DefensiveTeam
desc
PlayAttempted
Yards.Gained
sp
Touchdown
ExPointResult
TwoPointConv
DefTwoPoint
Safety
Onsidekick
PuntResult
PlayType
Passer
Passer_ID
PassAttempt
PassOutcome
PassLength
AirYards
YardsAfterCatch
QBHit
PassLocation
InterceptionThrown
Interceptor
Rusher
Rusher_ID
RushAttempt
RunLocation
RunGap
Receiver
Receiver_ID
Reception
ReturnResult
Returner
BlockingPlayer
Tackler1
Tackler2
FieldGoalResult
FieldGoalDistance
Fumble
RecFumbTeam
RecFumbPlayer
Sack
Challenge.Replay
ChalReplayResult
Accepted.Penalty
PenalizedTeam
PenaltyType
PenalizedPlayer
Penalty.Yards
PosTeamScore
DefTeamScore
ScoreDiff
AbsScoreDiff
HomeTeam
AwayTeam
Timeout_Indicator
Timeout_Team
posteam_timeouts_pre
HomeTimeouts_Remaining_Pre
AwayTimeouts_Remaining_Pre
HomeTimeouts_Remaining_Post
AwayTimeouts_Remaining_Post
No_Score_Prob
Opp_Field_Goal_Prob
Opp_Safety_Prob
Opp_Touchdown_Prob
Field_Goal_Prob
Safety_Prob
Touchdown_Prob
ExPoint_Prob
TwoPoint_Prob
ExpPts
EPA
airEPA
yacEPA
Home_WP_pre
Away_WP_pre
Home_WP_post
Away_WP_post
Win_Prob
WPA
airWPA
yacWPA
Season

In [10]:
#take a few columns to work with
nfl_data=nfl_data[[
    "Date",
    "GameID",
    "Drive",
    "qtr",
    "down",
    "time",
    "TimeUnder",
    "TimeSecs",
    "PlayTimeDiff",
    "SideofField"
]]

#get 5 rows
nfl_data.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT

**2. How many missing data points do we have**

Identify how many missing values we have in each column

In [19]:
#get total missing values per column
missing_values_count=nfl_data.isnull().sum()

#look at the first 10 columns
missing_values_count[0:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            22568
time               80
TimeUnder           0
TimeSecs           80
PlayTimeDiff      160
SideofField       192
dtype: int64

In [17]:
nfl_data.shape

(150888, 102)

That seems like alot, lets find the percentage of the values in our dataset were missing to give us a better sense of the scale of this problem

In [18]:
import numpy as np

In [21]:
#how many total missing values do we have
total_cells=np.prod(nfl_data.shape) #use numpy to multiply rows and columns
total_missing=missing_values_count.sum() #count all the missing values inthe dataframe


#percentage of data that is  missing
percent_missing=(total_missing/total_cells)*100

print(f"{percent_missing}%") #get the percentage of data missing

27.704466681428947%

**3. Figure out why the data is missing**

Perform *data intution* meaning loooking at your data and figuring out why it is the way it is and how that will affect your analysis.

**NOTE**:Is the most frastruting when your Noob

Intution Trigger ask yourself:
**Is this value missing beacuse it wasn't recorded or becuase it doesn't exist?**

If value was missing because it wasnt recorded you can try to guess what it may based on the other values in that column and row.(**Imputation**)

Lets take a closer look to the timessec column:

In [22]:
nfl_data['TimeSecs'].isnull().sum()

np.int64(80)

Looking at the documentation, the column has information on the number of seconds left in the game when the play was made.

We can note that this values were not recorded and that they exist, now we can try and guess rather than leaving them.

In [23]:
nfl_data['PenalizedTeam'].isnull().sum()

np.int64(140282)

PenalizedTeam column has anumber of missing values but there was no penalty then it doesnt make sense to guess them as they do not exist. For this column leave it empty or add third value like "neither" to replace null.

**N/B**: Read the documentation of the data set or if gotten from a third party reach out to them to get more information.

When performing **Careful data Analysis** take a close look at each column individually to figure out the best strategy for filling those missing values.

# **Quick Fixes**

**1. Drop missing values**

When in a hurry or dont have time to figure out what values are missing, one option you have is to remove any rows or columns that contain missing values.

**NOTE**: Not reccomended when working on important projects.

We can drop missing values using **dropna()** method.

In [24]:
#remove all rows that contain NA
nfl_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

😂😂That removed all the rows in our data as they all contained null value.

Lets remove columns that have a null values instead.

In [25]:
#remove columns with missing vals
columns_with_na_dropped=nfl_data.dropna(axis=1)

#display
columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Safety,Onsidekick,PlayType,PassAttempt,AirYards,YardsAfterCatch,QBHit,InterceptionThrown,RushAttempt,Reception
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,0,Kickoff,0,0,0,0,0,0,0
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,0,Pass,1,-3,8,0,0,0,1
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,0,Run,0,0,0,0,0,1,0
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,0,Pass,1,34,0,0,0,0,0
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,0,Punt,0,0,0,0,0,0,0

In [27]:
#confirm
columns_with_na_dropped.isnull().sum()

Date                  0
GameID                0
Drive                 0
qtr                   0
TimeUnder             0
ydstogo               0
ydsnet                0
PlayAttempted         0
Yards.Gained          0
sp                    0
Touchdown             0
Safety                0
Onsidekick            0
PlayType              0
PassAttempt           0
AirYards              0
YardsAfterCatch       0
QBHit                 0
InterceptionThrown    0
RushAttempt           0
Reception             0
dtype: int64

In [28]:
#just how much data did we lose?
print("Columns in original dataset: ", nfl_data.shape[1])

print("Columns with na's dropped: ", columns_with_na_dropped.shape[1])

Columns in original dataset:  102
Columns with na's dropped:  21

In [36]:
col_num_one=nfl_data.shape[1]

col_num_two=columns_with_na_dropped.shape[1]

print(col_num_two)
print(col_num_one)

difference=col_num_one-col_num_two
difference

21
102

81

We lost abit of our data but we successfully removed all the NaN's from our data.

**2. Filling missing values automatically**

Try and fill missing values using **fillna()** method. We specify what we want the NaN values to be replaced with.

In [29]:
#get small subset of the data
subset_nfl_data=nfl_data.loc[:,'EPA':'Season'].head()

#display
subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009.0
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009.0
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009.0
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009.0
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009.0

In [30]:
#replace all NA's with 0
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009.0
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009.0
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009.0
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009.0
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009.0

Make it more savvy and replace missing values with whenever value comes directly after it in the same column.

*Note*: Makes more sense in datasets where observation has some logic order to them.

In [31]:
#fill NA with value after it and when you get to end without value fill with 0
subset_nfl_data.fillna(method="bfill", axis=0).fillna(0)

/tmp/ipython-input-2710929530.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  subset_nfl_data.fillna(method="bfill", axis=0).fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009.0
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009.0
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009.0
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009.0
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009.0