# **Summary Functions and Maps**

When selecting data we want to work with from a dataFrame/Series, we apply more operations to our data to get the right input "just right" for the task at hand

In [1]:
import pandas as pd

In [ ]:
#load data
reviews=pd.read_csv('sample_data/reviews.csv', index_col=0)

#display
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
reviews.shape

(129971, 13)

In [ ]:
col_table=list(reviews.columns)
#get the column names
for i in col_table:
  print(i)

country
description
designation
points
price
province
region_1
region_2
taster_name
taster_twitter_handle
title
variety
winery

**Summary functions**

This functions restructure the data in some useful way. Example:

**describe() method**:Generates a high level summary of the attributes of the columns. Its *type-aware* meaning its output changes based on the data type of the input.

*NOTE*: Makes sence for numerical columns to use this

In [ ]:
#check the points column
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

**mean()**

Used to get the mean value in a numerical column

In [ ]:
#get mean for points column
reviews['points'].mean()

np.float64(88.44713820775404)

**unique()**

Method is used to get unique values in a column

In [ ]:
#get the unique values in taster_name
reviews['taster_name'].unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [ ]:
#To see a list of unique values and how often they occur in a dataset
reviews['taster_name'].value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

# **Maps**

A functions that takes one set of values and "maps" them to another set of values.

map() -Example we wanted to remean the scores the wines received to 0:

In [ ]:
reviews_points_mean=reviews['points'].mean()

reviews.points.map(lambda p:p - reviews_points_mean)

#we get a new series from our function above

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

**apply()**

Method is used when we want to transform a whole dataframe by calling a custom method on each row
.

In [ ]:
def remean_points(row):
  row.points=row.points-reviews_points_mean
  return row

#apply the above method to all the columns
reviews.apply(remean_points,axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
#EXAMPLE: Combining country and region information inthe dataset
reviews['country']+"-"+reviews['region_1']

0                     Italy-Etna
1                            NaN
2           US-Willamette Valley
3         US-Lake Michigan Shore
4           US-Willamette Valley
                   ...
129966                       NaN
129967                 US-Oregon
129968             France-Alsace
129969             France-Alsace
129970             France-Alsace
Length: 129971, dtype: object

**NOTE**: The above operators are faster tat map() and apply() because they use speed ups built into pandas. However, map() and apply() can do more advanced things like applying conditional logic.

**Map()**

Is very handy for applying operations to each element of a series.

*NOTE*: series is a column in a dataframe.

In [2]:
#Example- Mapping Series

#create a series of numbers
s=pd.Series([1,2,3,4,5,6,7])

#square each element inthe column
squared_s=s.map(lambda x:x**2)

#display
squared_s

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64

In [3]:
#Mapping with dictionary
#series of fruit
fruits=pd.Series(['apple','banana','mango','apple','banana'])

#map each fruit to a color
color_map={'apple':'red','banana':'yellow','mango':'orange'}

#run .map() method for the operation
fruit_colors=fruits.map(color_map)

#display
fruit_colors

0       red
1    yellow
2    orange
3       red
4    yellow
dtype: object

In [4]:
#Mapping with a function
names=pd.Series(['Allan','Mary','Alvin'])

#convert to lowercase using map()
lowercase_names=names.map(str.lower)

#display
lowercase_names

0    allan
1     mary
2    alvin
dtype: object

**Exercise:**

Count how many times "tropical" and "fruity" appear in the description column (ignoring capitalized versions).

In [5]:
data = {
    "description": [
        "This wine is fruity with tropical notes.",
        "A bold fruity flavor with hints of spice.",
        "Tropical aromas dominate this wine.",
        "Smooth and elegant with fruity undertones."
    ]
}

df = pd.DataFrame(data)
df

                                  description
0    This wine is fruity with tropical notes.
1   A bold fruity flavor with hints of spice.
2         Tropical aromas dominate this wine.
3  Smooth and elegant with fruity undertones.

In [6]:
#convert all descriptions to lowercase
df['description']=df['description'].map(str.lower)

In [7]:
#count occurences of tropical and fruity
descriptor_counts=pd.Series({
    'tropical':df['description'].str.count("tropical").sum(),
    'fruity':df['description'].str.count('fruity').sum()
})

In [8]:
#display
descriptor_counts

tropical    2
fruity      3
dtype: int64

**More Exercises**

In [9]:
#1. Square numbers
#Create a Series of numbers 1–5. Use .map() to get their cubes.

s=pd.Series([1,2,3,4,5,6])

#cube the numbers
cubed_s=s.map(lambda x:x**3)

#display
cubed_s

0      1
1      8
2     27
3     64
4    125
5    216
dtype: int64

In [13]:
#2 Maping with dictionary
#You have a Series of grades ["A", "B", "C", "A", "B"]. Map them to points:
grades=pd.Series(['A','B','C','A','B'])

#create dict to use
points={
    'A':4,
    'B':3,
    'C':2
}

#map grades to specific points to make a gpa
gpa=grades.map(points)

#display
gpa

0    4
1    3
2    2
3    4
4    3
dtype: int64

**3. Clean text with functions**

You have a Series of names: [" Alice ", " Bob", "Charlie "]. Use .map() to:

Strip whitespace

Convert to lowercase

In [14]:
name=pd.Series(['Alice  ','  Bob','Charlie'])

#remove white spaces and convert to lowercase
cleaned_name=name.map(lambda x:x.strip().lower())

#display
cleaned_name

0      alice
1        bob
2    charlie
dtype: object

**4. Apply Multiple Conditions**

You have numbers: [10, 25, 30, 45]. Map each number to:

"Small" if < 20

"Medium" if 20–40

"Large" if > 40

In [15]:
#create series
numbers=pd.Series([10,25,30,45])

#display
numbers

0    10
1    25
2    30
3    45
dtype: int64

In [18]:
def num_descip(nums):
  if nums>40:
    return "Large"
  elif nums>=20:
    return "Medium"
  elif nums<20:
    return "Small"

#map() method
manipulate_nums=numbers.map(num_descip)

In [19]:
#display
manipulate_nums

0     Small
1    Medium
2    Medium
3     Large
dtype: object

**apply() method**

apply() works on both: a Series and an entire dataframe

In [20]:
s=pd.Series([1,2,3,4,5])

#use apply to square the elements
s=s.apply(lambda x:x**2)

#display
s

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [22]:
#Apply on a Dataframe. COlumn wise
df=pd.DataFrame({
    "A":[1,2,3],
    "B":[10,20,30]
})
#view data frame
df

   A   B
0  1  10
1  2  20
2  3  30

In [23]:
#get sum of each column
col_sum=df.apply(sum,axis=0)

#display
col_sum

A     6
B    60
dtype: int64

In [24]:
#Apply on dataframe.Row-wise
row_sum=df.apply(sum,axis=1)

#display
row_sum

0    11
1    22
2    33
dtype: int64

In [25]:
#Apply to strings
names=pd.Series(['Allan','Mary','Alvin'])

lowercase_names=names.apply(str.lower)
#display
lowercase_names

0    allan
1     mary
2    alvin
dtype: object

In [27]:
#Apply accross columns
df=pd.DataFrame({
    "Math":[30,50,60],
    "Physics":[90,20,40]
})

#display
df

   Math  Physics
0    30       90
1    50       20
2    60       40

In [28]:
#calculate total marks of each student
df=df.apply(sum,axis=1)

In [29]:
df

0    120
1     70
2    100
dtype: int64