In [2]:
import pandas as pd

In [3]:
reviews=pd.read_csv("sample_data/reviews.csv")

#display
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# **Grouping and Sorting**

groupby() operation, allows us to group our data and then do something specific to the group the data is in.

**Groupwise analysis**

We can replicate what value_counts() byt doing:

In [4]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [5]:
#lets get the cheapest wine in each point value
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

Each group we generate as being a slice of our DataFrame containing only data with values that match.

The dataframe is accessible using **apply()** method, we can manipulate the data in any way we see fit.

In [8]:
reviews.groupby('winery').apply(lambda df:df.title.iloc[0])

/tmp/ipython-input-2319466332.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby('winery').apply(lambda df:df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [11]:
#best wine by country and province
reviews.groupby(['country','province']).apply(lambda df:df.loc[df.points.idxmax()])

/tmp/ipython-input-1086910443.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby(['country','province']).apply(lambda df:df.loc[df.points.idxmax()])

                            Unnamed: 0    country  \
country   province
Argentina Mendoza Province       82754  Argentina
          Other                  78303  Argentina
Armenia   Armenia                66146    Armenia
Australia Australia Other        37882  Australia
          New South Wales        85337  Australia
...                                ...        ...
Uruguay   Juanico                 9133    Uruguay
          Montevideo             15750    Uruguay
          Progreso               93103    Uruguay
          San Jose               39898    Uruguay
          Uruguay                39361    Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 14 columns]

**agg()**

Method allows us to run a bunch of different funcions on your dataframe simultaneously.

In [12]:
#simple statictical summary of the dataset as follows
reviews.groupby(['country']).price.agg([len,min,max])

/tmp/ipython-input-2681024424.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  reviews.groupby(['country']).price.agg([len,min,max])
/tmp/ipython-input-2681024424.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  reviews.groupby(['country']).price.agg([len,min,max])

                          len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   5.0   900.0
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0

In [15]:
col_df=list(reviews.columns)

for i in col_df:
  print(i)

Unnamed: 0
country
description
designation
points
price
province
region_1
region_2
taster_name
taster_twitter_handle
title
variety
winery

**Multi-indexes**

groupby() method sometimes results in what is called a multi-index.

A multi-index differs from regular index because it has multiple levels

In [17]:
#lets get the length of description
countries_reviewed=reviews.groupby(['country','province']).description.agg([len])

countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [18]:
mi=countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

**NOTE**: Often when dealing with multi-index methods we convert it back to a regular index, use **reset_index()** method.

In [19]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

**Sorting**

To get the data the data inthe order we want it we can sort it ourselves. **sort_values()** mthod is handy for this.

In [20]:
countries_reviewed=countries_reviewed.reset_index()

countries_reviewed.sort_values(by='len')

          country           province    len
386        Turkey  Elazığ-Diyarbakir      1
389        Turkey        Urla-Thrace      1
395            US             Hawaii      1
357  South Africa    Piekenierskloof      1
354  South Africa         Paardeberg      1
..            ...                ...    ...
409            US             Oregon   5373
227         Italy            Tuscany   5897
118        France           Bordeaux   5941
415            US         Washington   8639
392            US         California  36247

[425 rows x 3 columns]

In [21]:
#set it to sort in descending order
countries_reviewed.sort_values(by='len',ascending=False)

    country          province    len
392      US        California  36247
415      US        Washington   8639
118  France          Bordeaux   5941
227   Italy           Tuscany   5897
409      US            Oregon   5373
..      ...               ...    ...
389  Turkey       Urla-Thrace      1
48   Canada      Canada Other      1
40   Brazil  Serra do Sudeste      1
395      US            Hawaii      1
399      US          Kentucky      1

[425 rows x 3 columns]

In [22]:
#to sort by index let use the method by default
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [24]:
#we can sort by more than one column
countries_reviewed.sort_values(by=['country','len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
2      Armenia           Armenia     2
6    Australia          Tasmania    42
4    Australia   New South Wales    85
..         ...               ...   ...
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
420    Uruguay           Juanico    12
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]

# **Group_by() method**

Its like saying **split my data into groups do something to each group, then combine the results**

**Split-Apply-combine**

You split the data into groups, apply an operation(like sum or mean), then combine the results back.

In [25]:
#df
df=pd.DataFrame({
    "Category":['A','A','B','B','C'],
    "Value":[10,20,30,40,50]
})

#display
df

  Category  Value
0        A     10
1        A     20
2        B     30
3        B     40
4        C     50

In [26]:
#sum values by category
grouped_df=df.groupby('Category').Value.sum()

In [27]:
#display
grouped_df

Category
A    30
B    70
C    50
Name: Value, dtype: int64

We are also able to perform other functions like **mean(), max(), min()**

In [29]:
means_df=df.groupby('Category').Value.mean()

#display
means_df

Category
A    15.0
B    35.0
C    50.0
Name: Value, dtype: float64

We can use **agg()** method and perform multiple stats at once

In [30]:
agg_result=df.groupby("Category").Value.agg(['sum','mean','max','min'])

#display
agg_result

          sum  mean  max  min
Category
A          30  15.0   20   10
B          70  35.0   40   30
C          50  50.0   50   50

You can group by more than one column at once

In [32]:
df2 = pd.DataFrame({
    "Team": ["A", "A", "B", "B", "C", "C"],
    "Year": [2020, 2021, 2020, 2021, 2020, 2021],
    "Points": [10, 15, 20, 25, 30, 35]
})

df2

  Team  Year  Points
0    A  2020      10
1    A  2021      15
2    B  2020      20
3    B  2021      25
4    C  2020      30
5    C  2021      35

In [33]:
#multiple columns groupby
multi_cols=df2.groupby(['Team','Year']).Points.sum()

In [34]:
#display
multi_cols

Team  Year
A     2020    10
      2021    15
B     2020    20
      2021    25
C     2020    30
      2021    35
Name: Points, dtype: int64

In [36]:
mi=multi_cols.index  #the result isa multi-level index(Team+Year)
type(mi)

pandas.core.indexes.multi.MultiIndex

We can also apply our own custom python functions using the **apply() method** as seen below:

In [37]:
#subtract max value with the min value
def value_range(x):
  return x.max()-x.min()

range_result=df.groupby('Category').Value.apply(value_range)

#display
range_result

Category
A    10
B    10
C     0
Name: Value, dtype: int64

**Real-World Example (Wine-style 🍷)**

In [38]:
wine_df = pd.DataFrame({
    "wine_type": ["red", "red", "white", "white", "red"],
    "points": [88, 92, 85, 90, 95]
})

wine_df

  wine_type  points
0       red      88
1       red      92
2     white      85
3     white      90
4       red      95

In [39]:
#lets compute the average points per wine type
avg_points=wine_df.groupby('wine_type').points.mean()

#display
avg_points

wine_type
red      91.666667
white    87.500000
Name: points, dtype: float64

**Sorting in pandas (sort_values & sort_index)**

You can sort a data in pandas either by values or by index

**sort_values()** sorts by columns

In [40]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Allan", "Mary", "John"],
    "Age": [25, 30, 20]
})

# Sort by Age ascending
df.sort_values("Age")

    Name  Age
2   John   20
0  Allan   25
1   Mary   30

In [41]:
#sort in descending order
df.sort_values("Age", ascending=False)

    Name  Age
1   Mary   30
0  Allan   25
2   John   20

**sort_index()** sorts by row index

In [42]:
df.sort_index()

    Name  Age
0  Allan   25
1   Mary   30
2   John   20